### ISSUE TITLE
Issue with new lemmy_client

### ISSUE THREAD

**Issue by jim-taylor-business** [LemmyNet/lemmy-ui-leptos#22]
@SleeplessOne1917 @dessalines 

i was unable to get the new lemmy client to make any successful request apart from the home page content (list_posts) on the server side only.

i noticed the home page content has been commented out completely so i assume this was a known issue.

i have left all the code there and only added some prototype code to add the authentication header.

**Comment by dessalines** [comment]
I'll try to get this fixed within a few days, I'm guessing it has to do with auth?

**Comment by jim-taylor-business** [comment]
i think the server side may have had some issues with switching between voyager and local dev lemmy instances

the browser side was never implemented (as the code was commented out) and i couldn't find a way to instantiate it in a functional way

having had a chance to think about it - it seems a little odd running a proxy through the front end service. in the case of the matrix chat system a separate proxy service (nginx or similar) is used to pass through requests to both the front end and back end services. i have seen this same architecture in many web apps. it can easily be used in dev and production environments.

the other improvements to how the http clients (both browser and server) are used do make sense.

**Comment by SleeplessOne1917** [comment]
I'm working on a branch that should resolve this issue.
