### ISSUE TITLE
Preferred icon pack(s)?

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui-leptos#29]
I noticed we're currently using icons from the charm icon pack, but it looks like our icon library supports a lot of different icon packages: https://github.com/Carlosted/icondata#icon-packages

It might be good to standardize or pick which ones we like going forward.

I've always been partial to either [feather icons](https://feathericons.com/), but tailwind's [hero icons](https://heroicons.com/) look like they might be a good choice too.

**Comment by SleeplessOne1917** [comment]
I found [phosphor-leptos](https://github.com/SorenHolstHansen/phosphor-leptos) recently. It seems like it's more actively maintained than leptos-icons and leptos_heroicons. The [icon family itself](https://phosphoricons.com/) is very versatile and should save us from needing to mix and match icons from different families.

**Comment by dessalines** [comment]
Sounds good to me.

**Comment by SleeplessOne1917** [comment]
I think we've settled on using phosphor icons as an SVG sprite for the time being.
