### ISSUE TITLE
Make playwright testing work accross machines

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy-ui-leptos#56]
I use an Arch spin as my daily driver, and playwright tests are not supported on that platform. This makes it impossible for me to run tests locally. We definitely want end to ends tests to make sure we don't introduce regressions. There are [docs for running playwright in docker](https://playwright.dev/docs/docker), which seems like the most obvious viable option.

**Comment by dessalines** [comment]
Agree, testing in docker makes the most sense.
